repos:
  - repo: local
    hooks:
      - id: markdown-lint
        name: markdown-lint
        language: system
        entry: markdownlint
        types: [markdown]
      - id: shell-lint
        name: shell-lint
        language: system
        entry: shellcheck
        types: [shell]
      - id: yaml-lint
        name: yaml-lint
        language: system
        entry: yamllint
        types: [yaml]
