repos:
- repo: local
  hooks:
  - id: shellcheck
    name: shellcheck
    language: system
    entry: shellcheck
    types: [shell]
  - id: markdownlint
    name: markdownlint
    language: system
    entry: markdownlint
    types: [markdown]
